### ISSUE TITLE
nginx example fails with AttributeError

### ISSUE THREAD

**Issue by asheplyakov** [stb-tester/apt2ostree#5]
```
$ git clone git://github.com/stb-tester/apt2ostree.git
$ cd apt2ostree/examples/nginx
$ mkdir -p _build/ostree
$ ./configure.py
Traceback (most recent call last):
  File "./configure.py", line 48, in <module>
    sys.exit(main(sys.argv))
  File "./configure.py", line 33, in main
    ubuntu_apt_sources("xenial"))
  File "./../../apt2ostree/apt.py", line 362, in build_image
    stage_2 = self.second_stage(stage_1, apt_source[0].architecture)
AttributeError: 'str' object has no attribute 'architecture'
```

**Comment by wmanley** [comment]
Closed by #6.  Thanks.
